# NOTE - use the file in templates/travis.yml as the starting point for your project's .travis.yml file
#
# Copyright (c) 2012 VMware, Inc. All Rights Reserved <dhenrich@vmware.com>.
# Copyright (C) 2014-2015 GemTalk Systems LLC <dale.henrichs@gemtalksystems.com>
#

language: erlang

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c59e6bffa0b41a693676 # GsDevKit/chat (public)
    on_success: always # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

env:
   - ST=Pharo-5.0
   - ST=Squeak-Trunk SCREENSHOT=60
   - ST=GemStone-3.2.7

   - ST=PharoCore-1.1
   - ST=PharoCore-1.2
   - ST=PharoCore-1.3  # NOTE: using build 13323, see Issue #69 for later builds
   - ST=Pharo-1.4
   - ST=Pharo-2.0 
   - ST=Pharo-3.0
   - ST=Pharo-4.0
   - ST=Squeak-4.3
   - ST=Squeak-4.4
   - ST=Squeak-4.5
   - ST=Squeak-4.6
   - ST=GemStone-2.4.4.1
   - ST=GemStone-2.4.5
   - ST=GemStone-2.4.6
   - ST=GemStone-3.0.1
   - ST=GemStone-3.1.0.2
   - ST=GemStone-3.1.0.6
   - ST=GemStone-3.2.0

matrix:
   allow_failures:
   - env: ST=Squeak-Trunk SCREENSHOT=60

install:
   - export PROJECT_HOME="$(pwd)"
   - source build_env_vars
   - ./build_image.sh

# use -verbose flag to control whether or not transcript is dumped
# to travis log
script: ./testBuilderCI.sh  -verbose
