# NOTE - use the file in templates/travis.yml as the starting point for your project's .travis.yml file

language: erlang

env:
   - ST=PharoCore-1.3
   - ST=Pharo-1.4
   - ST=Pharo-2.0
   - ST=Squeak4.3 # ensure that obsolete platform name Squeak4.3 works
   - ST=Squeak-4.3
   - ST=Squeak-4.4

install:
   - source build_env_vars
#   - ./build_clone.sh -g "git://github.com/dalehenrich/metacello-work.git"
   - ./build_image.sh

script:
   - ./build.sh -i $ST -s latAmMirror.st -m -f "$BUILDER_CI_HOME/tests/travisCI.st" -o travisCI
   - cd "${BUILD_PATH}/travisCI/"
   - ls -altr *
   - if ( test -e PharoDebug.log ); then cat TravisTranscript.txt; fi
   - if ( test -e PharoDebug.log ); then cat PharoDebug.log; fi
   - if ( test -e PharoDebug.log ); then die; fi
   - if ( test -e SqueakDebug.log ); then cat TravisTranscript.txt; fi
   - if ( test -e SqueakDebug.log ); then cat SqueakDebug.log; fi
   - if ( test -e SqueakDebug.log ); then die; fi
   - if ( test -e TravisCISuccess.txt ); then cat TravisCISuccess.txt; fi
   - if ( test -e TravisCIFailure.txt ); then cat TravisCIFailure.txt; fi
   - if ( test -e TravisCIFailure.txt ); then die; fi
   - cat TravisTranscript.txt

